Eval [
    FileStream
        fileIn: 'src/Logging.st';
        fileIn: 'src/VLR.st';
        fileIn: 'src/HLR.st';
        fileIn: 'src/BSCConfig.st';
        fileIn: 'src/BSCListener.st';
        fileIn: 'src/BSCSCCPHandler.st';
        fileIn: 'src/GSMAuthenticator.st';
        fileIn: 'src/GSMProcessor.st';
        fileIn: 'src/GSMMOCall.st';
        fileIn: 'src/GSMLURequest.st';
        fileIn: 'src/GSMCMServiceRequest.st';
        fileIn: 'src/GSMEmergencySetup.st';
        fileIn: 'src/BSCIPAConnection.st';
        fileIn: 'src/PagingManager.st';
        fileIn: 'src/MSC.st';
        fileIn: 'src/SIPCall.st'.

"
"
]
